apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-broker
  name: inventory-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-broker
  template:
    metadata:
      labels:
        app: inventory-broker
    spec:
      containers:
        - image: 'cremerfc/inventory-broker:latest'
          name: inventory-broker
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-broker-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: inventory-broker
  type: LoadBalancer
