apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-broker
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: inventory-broker
    tags.datadoghq.com/version: "1.0"
  name: inventory-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-broker
  template:
    metadata:
      labels:
        app: inventory-broker
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: inventory-broker
        tags.datadoghq.com/version: "1.0"
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - image: 'cremerfc/inventory-broker:main'
          name: inventory-broker
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-broker-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: inventory-broker
  type: LoadBalancer
